### ISSUE TITLE
"Module file's minimum deployment target is ios9.0 v9.0"

### ISSUE THREAD

**Issue by Gurpartap** [RxSwiftCommunity/RxAlamofire#43] opened 2016-09-21 04:21 UTC
In a blank new project with only RxAlamofire from after the Swift 3.0 PR merge on Xcode 8.0 (8A218a).

```
$ cat Podfile
```

``` ruby
target "Example" do
    platform :ios, "9.0"
    use_frameworks!

    pod "RxAlamofire", git: "https://github.com/RxSwiftCommunity/RxAlamofire", branch: "develop"
end
```

![screen shot 2016-09-21 at 9 49 21 am](https://cloud.githubusercontent.com/assets/39792/18697655/e6a0a544-7fe0-11e6-9098-7d464e76203c.png)

**Comment by silvansky** [comment] 2016-09-23 15:04
Any workaround?

**Comment by kzaher** [comment] 2016-09-23 17:37
Hi @Gurpartap ,

I don't know, this same Podfile works for me.

```
pod --version
1.1.0.beta.2
```

**Comment by silvansky** [comment] 2016-09-28 14:04
pod --version
    1.1.0.rc.2

But the problem is still present.

**Comment by nverinaud** [comment] 2016-12-09 09:02
Same here using carthage...

**Comment by nverinaud** [comment] 2016-12-09 09:16
It seems to be fixed in master branch. Waiting for a `3.0.3` tag and release 😬

**Comment by tkunzema** [comment] 2017-01-05 08:30
Still present in january 2017 ...

**Comment by ened** [comment] 2017-01-10 02:45
The root cause may happen because Alamofires swift3 branch switched to a 9.0 minimum deployment target while RxAlamofire is still on 8.0?

**Comment by scoreyou** [comment] 2017-05-23 18:00
Still present :(

**Closed** 2017-05-25 19:46 UTC
