### ISSUE TITLE
rx_response{_} disposing issue

### ISSUE THREAD

**Issue by volkzayaz** [RxSwiftCommunity/RxAlamofire#19] opened 2016-03-01 18:32 UTC
Hello, guys. 

I was using `rx_responseData()` method for downloading imageData for some of my CollectionViewCells.
I set up Observable disposing in prepareForReuse method. However I noticed, that `RxAlamofire` did not cancel Request on disposing and was still loading data in background.

Looking inside I saw that methods of `rx_response{_}` family are created as observables with dispose type `NopDisposable.instance`. Specifically methods:

    rx_request
    rx_responseResult
    rx_result
    rx_progress

Changing dispose type to 

       AnonymousDisposable {
                self.cancel()
       }

cancels request just fine.

Is it a bug for using `NopDisposable.instance` in those methods or am I missing something?

**Comment by werediver** [comment] 2016-06-09 09:27
I think it's really an issue and should be fixed.

@volkzayaz Could you please clarify whether the disposable should strongly capture the request or capture should be weak? (I'm new to RX and really not sure)

**Comment by kzaher** [comment] 2016-06-09 09:59
Hi guys,

I think this is by design, you shouldn't manually create alamofire `Request` object.

```swift
_ = manager.rx_request(.GET, stringURL)
    .flatMap {
        $0
            .validate(statusCode: 200 ..< 300)
            .validate(contentType: ["text/json"])
            .rx_responseString()
    }
    .observeOn(MainScheduler.instance)
    .subscribe { print($0) }
```

The intended use of those methods is inside `flatMap` to select correct result.

Cancelling `Request` from those sequences would be wrong, because you could have two observers observing `rx_request`, and in case one of them disposes it's subscription, it will mirror the cancellation on the other observer.

Integrating with Alamofire is little problematic because there isn't a separate request object and request executor, so you cannot easily separate pure definition of the network operation, from execution and retry logic as far as I'm aware of. 

Maybe something has changed in newer versions that we missed while writing this. Please take a look at usage examples in `README.md`

**Comment by werediver** [comment] 2016-06-09 10:05
I think it's ok to mirror cancelation of a shared observable to all observers. If it's not what you want, you create new observables. Am I missing something?

**Comment by kzaher** [comment] 2016-09-23 17:41
> I think it's ok to mirror cancelation of a shared observable to all observers.

No IMHO.

**Closed by kzaher** 2016-09-23 17:41 UTC
